---
- name: create file using j2
  hosts: dev
  become: yes
  tasks:
    - name: create file
      file: 
        path: /etc/myvhost
        state: touch
    - name: add template
      template: 
        src: server_list.j2
        dest: /etc/myvhost

