---
- name: create LVM
  hosts: all
  become: yes
  tasks:
    - name: create LVM
      block:
        - name: Create LVM of 1500MiB size
          lvol:
            vg: research
            lv: data
            size: 1500m
      rescue: 
        - debug:
            msg: "The is no space to create 1500MiB of LVM. Trying to create 800MiB "
        - name: Create LVM of 800MiB size
          lvol:
            vg: research
            lv: data 
            size: 800m
          register: vg_group
      always:      
        - name: display messsage
          debug:
            msg: " volume group research is not found "
          when: vg_group is not succeeded        
